"""
suggest_validation_rules.py
-----------------------------
AI-assisted validation-rule authoring: given a table's column names,
types, and a small sample of real values, asks the local LLM to DRAFT
candidate Pandera checks - accelerating the boring part of writing a
validation suite (staring at a new table guessing plausible ranges)
without ever auto-applying anything.

This is deliberately human-in-the-loop: the output is written to a
review file, not wired into the validation suite. A data engineer reads
it, keeps what's sensible, discards what isn't, and only then adds it
to validation/pandera_checks.py by hand. This mirrors how AI-assisted
tooling is actually used responsibly on real data teams in 2025/2026 -
as a drafting aid for a human who stays the final reviewer, not as an
unsupervised decision-maker over what gets treated as "valid" data.

Usage:
    python rag/suggest_validation_rules.py raw_orders
"""

import sys
from pathlib import Path

import duckdb
import ollama

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "database" / "warehouse.duckdb"
OUT_DIR = ROOT / "reports" / "ai_suggested_rules"
OUT_DIR.mkdir(parents=True, exist_ok=True)

OLLAMA_MODEL = "qwen2.5:0.5b"

PROMPT_TEMPLATE = """Table name: {table_name}
Columns: {columns}

Sample rows:
{sample_rows}

Task: write one validation rule for EACH column listed above. For number columns, give a min and
max value based on what you see in the sample rows. For text columns, list the exact values you
see. Do not invent column names that are not listed above.
Format: "<column_name>: <rule>"
"""


def suggest_rules_for_table(table_name: str, model: str = OLLAMA_MODEL) -> str:
    conn = duckdb.connect(str(DB_PATH), read_only=True)
    schema_df = conn.execute(f"DESCRIBE {table_name}").fetchdf()
    sample_df = conn.execute(f"SELECT * FROM {table_name} USING SAMPLE 5 ROWS").fetchdf()
    conn.close()

    columns = ", ".join(f"{r.column_name}: {r.column_type}" for r in schema_df.itertuples())
    sample_rows = sample_df.to_string(index=False)

    prompt = PROMPT_TEMPLATE.format(table_name=table_name, columns=columns, sample_rows=sample_rows)

    response = ollama.chat(
        model=model,
        messages=[{"role": "user", "content": prompt}],
        options={"temperature": 0.2, "num_predict": 300},
    )
    suggestions = response["message"]["content"].strip()

    out_path = OUT_DIR / f"{table_name}_suggested_rules.md"
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(f"# AI-Suggested Validation Rules: {table_name}\n\n")
        f.write("**Status: DRAFT - requires human review before adoption.** These suggestions were "
                 "generated by a local LLM (qwen2.5:0.5b) from the table's schema and a small sample "
                 "of real rows. They are a starting point for a data engineer to review, not a "
                 "validated or automatically-applied ruleset.\n\n")
        f.write(f"## Columns\n{columns}\n\n")
        f.write(f"## AI-Drafted Suggestions\n{suggestions}\n")

    print(f"Suggestions for '{table_name}' written to {out_path}\n")
    print(suggestions)
    return suggestions


if __name__ == "__main__":
    table = sys.argv[1] if len(sys.argv) > 1 else "raw_orders"
    suggest_rules_for_table(table)
